[admiral]
items = ["left", "workspaces",
         "center", "title",
         "right", "internet", "space", "batteries", "space", "clock"]

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[space]
path = "echo -e '  '"
static = true

[workspaces]
path = "bspwm-w"

[title]
path = "xtitle -s -t 100"

[batteries]
path = "battery"
reload = 10

[clock]
path = "date '+%H%M '"
reload = 1

[internet]
path = "internet"
reload = 60
