#!/bin/sh

while read -r lbl dest; do
	a "g$lbl"="cd $dest"
done <<EOF
H $HOME
B $HOME/bin
E $HOME/.config
S $HOME/src
s $HOME/.local/share
O $HOME/ext
W $HOME/med/wall
D $HOME/doc
d $HOME/dl
M $HOME/med
w $HOME/bin/wrap
x $HOME/bin/x
X $HOME/.config/xorg.d
h $HOME/.config/home.d
mn /mnt
EOF
