#!/bin/sh

xhost +local:

[ -z "$(pidof plumber)" ] && plumber

# Load Xresources if present
xres="$XDG_CONFIG_HOME/xorg.d/Xresources"
[ -f "$xres" ] && xrdb "$xres"

# Set cursor to something good
xsetroot -cursor_name left_ptr

#hsetroot -solid '#414A4C'
hsetroot -fill "$WALL" &

# Colemak TODO: set this in X config instead
setxkbmap -layout us colemak

# Starting low battery notifications daemon
lowbatteryd "$LOWBATTERYD_INTERVAL" "$BATTERY_CRITICAL" &

# Starting the wm
sxhkd -m 1 &
exec "$WM"
